/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/espiral.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/espiral.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Spiral002.geometry} material={materials.Spiral} position={[-0.437, 0.827, 44.286]} />
      <mesh geometry={nodes.Cube_E1001.geometry} material={materials.Etapa_Inactiva} position={[8.455, 0.89, 43.561]} scale={1.3} />
      <mesh geometry={nodes.Cube_E1002.geometry} material={materials.Etapa_Inactiva} position={[-10.93, 4.349, 43.561]} scale={1.3} />
      <mesh geometry={nodes.Cube_E3001.geometry} material={materials.Etapa_Inactiva} position={[-0.503, 6.408, 55.74]} scale={1.3} />
      <mesh geometry={nodes.Cube_E4001.geometry} material={materials.Etapa_Inactiva} position={[3.275, 9.688, 31.997]} scale={1.3} />
      <mesh geometry={nodes.Cube_E5001.geometry} material={materials.Etapa_Inactiva} position={[-12.233, 12.511, 52.109]} scale={1.3} />
      <mesh geometry={nodes.Cube_E6001.geometry} material={materials.Etapa_Inactiva} position={[14.599, 15.712, 40.562]} scale={1.3} />
    </group>
  )
}

useGLTF.preload('/espiral.glb')
