/**
 * INFRASTRUCTURE — Datos del manifiesto multimedia
 *
 * Fuente TS local del manifiesto (`satisfies MediaManifest`, chequeo en
 * compilación, cero costo en runtime). Es la única fuente de rutas y
 * proveedores multimedia de la cartilla.
 *
 * Todas las rutas locales apuntan a archivos verificados presentes en
 * `public/` (inventario de la fase de planificación); las entradas
 * `"pending"` no tienen archivo en ningún lado todavía.
 */
import { mediaKey } from "@domain/content/value-objects/MediaKey";
import type { MediaManifest } from "@domain/media/MediaAsset";
import { TRANSITION_PLAYBACK, SUMMARY_VIDEO_PLAYBACK } from "@domain/media/MediaAsset";

export const MEDIA_MANIFEST = {
  // ── Personaje / guía ───────────────────────────────────────────────────────
  // ── Poses de LaIA ────────────────────────────────────────────────────────
  [mediaKey("laia.pose.neutral")]: {
    key: mediaKey("laia.pose.neutral"),
    kind: "image",
    provider: "local",
    ref: "/media/compartido/imagenes/laia-neutral.png",
    availability: "available",
    alt: "LaIA",
    fallback: "LaIA",
  },
  [mediaKey("laia.pose.explaining")]: {
    key: mediaKey("laia.pose.explaining"),
    kind: "image",
    provider: "local",
    ref: "/media/compartido/imagenes/laia-explicando.png",
    availability: "available",
    alt: "LaIA explicando",
    fallback: "LaIA",
  },
  [mediaKey("laia.pose.holo")]: {
    key: mediaKey("laia.pose.holo"),
    kind: "image",
    provider: "local",
    ref: "/media/compartido/imagenes/laia-holograma.png",
    availability: "available",
    alt: "LaIA en proyección holográfica",
    fallback: "LaIA",
  },
  [mediaKey("laia.pose.triumphant")]: {
    key: mediaKey("laia.pose.triumphant"),
    kind: "image",
    provider: "local",
    ref: "/media/compartido/imagenes/laia-triunfante.png",
    availability: "available",
    alt: "LaIA celebrando",
    fallback: "LaIA",
  },

  // ── Marca / portada (Fase 7) ───────────────────────────────────────────────
  [mediaKey("brand.logoRed")]: {
    key: mediaKey("brand.logoRed"),
    kind: "image",
    provider: "local",
    ref: "/media/compartido/imagenes/logo-uao-rojo.webp",
    availability: "available",
    alt: "Universidad Autónoma de Occidente",
    fallback: "UAO",
  },
  [mediaKey("ui.introHeroBackground")]: {
    key: mediaKey("ui.introHeroBackground"),
    kind: "image",
    provider: "local",
    ref: "/media/compartido/imagenes/portada-introduccion.webp",
    availability: "available",
    fallback: "",
  },

  // ── Etapa 2 ────────────────────────────────────────────────────────────────
  [mediaKey("stage2.criteriaInfographic")]: {
    key: mediaKey("stage2.criteriaInfographic"),
    kind: "image",
    provider: "local",
    ref: "/media/etapa-2/imagenes/criterios-posibilidades.webp",
    availability: "available",
    width: 2560,
    height: 1440,
    description: "Infografía: cómo se miran las posibilidades (seis criterios).",
    fallback: "La infografía de criterios estará disponible próximamente.",
  },
  [mediaKey("stage2.comparisonExample")]: {
    key: mediaKey("stage2.comparisonExample"),
    kind: "image",
    provider: "local",
    ref: "/media/etapa-2/imagenes/comparacion-herramientas.webp",
    availability: "available",
    width: 2560,
    height: 2228,
    description: "Infografía del ejemplo comparativo: tres posibilidades de IA para fortalecer un debate.",
    fallback: "El ejemplo comparativo estará disponible próximamente.",
  },
  [mediaKey("stage2.pughMatrix")]: {
    key: mediaKey("stage2.pughMatrix"),
    kind: "download",
    provider: "local",
    ref: "/media/etapa-2/descargables/matriz-pugh/matriz-pugh.pdf",
    availability: "available",
    downloadName: "matriz-pugh.pdf",
    description: "Matriz de Pugh para comparar herramientas de GenAI frente a criterios pedagógicos, éticos, críticos, de accesibilidad e integración.",
    fallback: "La Matriz de Pugh estará disponible para descarga próximamente.",
  },
  [mediaKey("stage2.pughMatrixPreview")]: {
    key: mediaKey("stage2.pughMatrixPreview"),
    kind: "image",
    provider: "local",
    ref: "/media/etapa-2/descargables/matriz-pugh/vista-previa.png",
    availability: "available",
    width: 1687,
    height: 1093,
    alt: "Previsualización de la Matriz de Pugh con criterios, pesos, referencia y tres herramientas de GenAI para comparación ponderada.",
    description: "Previsualización de la Matriz de Pugh para el análisis de herramientas de GenAI.",
    fallback: "La vista previa de la Matriz de Pugh estará disponible próximamente.",
  },

  // ── Etapa 3 ────────────────────────────────────────────────────────────────
  [mediaKey("stage3.designCanvas")]: {
    key: mediaKey("stage3.designCanvas"),
    kind: "download",
    provider: "local",
    ref: "/media/etapa-3/descargables/canvas-diseno/canvas-diseno.pdf",
    availability: "available",
    downloadName: "canvas-etapa-3-diseno.pdf",
    description: "Canvas de diseño de experiencia mediada por GenAI (PDF).",
    fallback: "El Canvas de diseño estará disponible para descarga próximamente.",
  },
  [mediaKey("stage3.designCanvasPreview")]: {
    key: mediaKey("stage3.designCanvasPreview"),
    kind: "image",
    provider: "local",
    ref: "/media/etapa-3/descargables/canvas-diseno/vista-previa.png",
    availability: "available",
    width: 1754,
    height: 1464,
    alt: "Previsualización del Canvas de la Etapa 3 para diseñar una experiencia de aprendizaje mediada por IA.",
    description: "Previsualización del Canvas de diseño de experiencia mediada por GenAI.",
    fallback: "La vista previa del canvas estará disponible próximamente.",
  },
  [mediaKey("stage3.experienceMatrix")]: {
    key: mediaKey("stage3.experienceMatrix"),
    kind: "download",
    provider: "local",
    ref: "/media/etapa-3/descargables/matriz-experiencia/matriz-experiencia.pdf",
    availability: "available",
    downloadName: "matriz-de-la-experiencia.pdf",
    description: "Matriz para mapear el antes, durante y después de la experiencia, con acciones del estudiante, acciones docentes, recursos y tiempos.",
    fallback: "La Matriz de la experiencia estará disponible próximamente.",
  },
  [mediaKey("stage3.experienceMatrixPreview")]: {
    key: mediaKey("stage3.experienceMatrixPreview"),
    kind: "image",
    provider: "local",
    ref: "/media/etapa-3/descargables/matriz-experiencia/vista-previa.png",
    availability: "available",
    width: 3455,
    height: 1102,
    alt: "Previsualización de la Matriz de la experiencia organizada en antes, durante y después, con filas para acciones del estudiante, docente, recursos y tiempos.",
    description: "Previsualización de la Matriz de la experiencia de aprendizaje.",
    fallback: "La vista previa de la Matriz de la experiencia estará disponible próximamente.",
  },

  // ── Etapa 4 ────────────────────────────────────────────────────────────────
  [mediaKey("stage4.controlRoom")]: {
    key: mediaKey("stage4.controlRoom"),
    kind: "image",
    provider: "local",
    ref: "/media/etapa-4/imagenes/sala-control.webp",
    availability: "available",
    width: 2560,
    height: 1142,
    description:
      "Infografía: sala de control del alistamiento — verificación técnica, pedagógica y ético-emocional para llegar a una experiencia lista para el aula.",
    fallback: "La infografía de la sala de control estará disponible próximamente.",
  },
  [mediaKey("stage4.section2Media")]: {
    key: mediaKey("stage4.section2Media"),
    kind: "image",
    provider: "local",
    ref: "/media/etapa-4/imagenes/lista-alistamiento.webp",
    availability: "available",
    width: 2560,
    height: 1085,
    description:
      "Infografía: checklist de preparación — herramienta funcionando, instrucciones claras, reglas de aula, plan de actividad y acompañamiento previsto.",
    fallback: "El recurso de la sección 2 estará disponible próximamente.",
  },
  [mediaKey("stage4.readinessCanvas")]: {
    key: mediaKey("stage4.readinessCanvas"),
    kind: "download",
    provider: "local",
    ref: "/media/etapa-4/descargables/canvas-alistamiento/canvas-alistamiento.pdf",
    availability: "available",
    downloadName: "canvas-etapa-4-alistamiento.pdf",
    description: "Canvas de alistamiento de la experiencia (PDF).",
    fallback: "El Canvas de alistamiento estará disponible para descarga próximamente.",
  },
  [mediaKey("stage4.readinessCanvasPreview")]: {
    key: mediaKey("stage4.readinessCanvasPreview"),
    kind: "image",
    provider: "local",
    ref: "/media/etapa-4/descargables/canvas-alistamiento/vista-previa.png",
    availability: "available",
    width: 1754,
    height: 1464,
    alt: "Previsualización del Canvas de la Etapa 4 para alistar una experiencia de aprendizaje mediada por IA.",
    description: "Previsualización del Canvas de alistamiento de la experiencia.",
    fallback: "La vista previa del Canvas de alistamiento estará disponible próximamente.",
  },

  // ── Etapa 5 ────────────────────────────────────────────────────────────────
  [mediaKey("stage5.classroomSimulation")]: {
    key: mediaKey("stage5.classroomSimulation"),
    kind: "video",
    provider: "http",
    ref: "/etapa-5/simulacion.mp4",
    availability: "pending",
    description: "Simulación de aula interactiva.",
    fallback: "video: simulación de aula (.mp4) — pendiente de subir",
    playback: TRANSITION_PLAYBACK,
  },
  [mediaKey("stage5.teacherAsMediator")]: {
    key: mediaKey("stage5.teacherAsMediator"),
    kind: "video",
    provider: "http",
    ref: "/etapa-5/mediador.mp4",
    availability: "pending",
    description: "Animación de acciones docentes durante el despliegue.",
    fallback: "video: el docente como mediador (.mp4) — pendiente de subir",
    playback: TRANSITION_PLAYBACK,
  },
  [mediaKey("stage5.teacherAsMediatorInfographic")]: {
    key: mediaKey("stage5.teacherAsMediatorInfographic"),
    kind: "image",
    provider: "local",
    ref: "/media/etapa-5/imagenes/docente-mediador.webp",
    availability: "available",
    width: 2560,
    height: 1769,
    description:
      "Infografía: el docente como mediador — guía, observa, aclara, interviene y protege el propósito de la experiencia.",
    fallback: "La infografía del docente mediador estará disponible próximamente.",
  },
  [mediaKey("stage5.criticalMomentsInfographic")]: {
    key: mediaKey("stage5.criticalMomentsInfographic"),
    kind: "image",
    provider: "local",
    ref: "/media/etapa-5/imagenes/momentos-criticos.webp",
    availability: "available",
    width: 2560,
    height: 2207,
    description:
      "Infografía: momentos críticos durante la experiencia — dificultades cognitivas, dilemas éticos, uso acrítico, fallas técnicas e instrucciones poco claras.",
    fallback: "La infografía de momentos críticos estará disponible próximamente.",
  },
  [mediaKey("stage5.rail.1")]: {
    key: mediaKey("stage5.rail.1"),
    kind: "image",
    provider: "local",
    ref: "/media/etapa-5/imagenes/evidencia-1.webp",
    availability: "available",
    description: "Evidencia 1: dudas de estudiantes.",
    fallback: "Evidencia 1 — próximamente.",
  },
  [mediaKey("stage5.rail.2")]: {
    key: mediaKey("stage5.rail.2"),
    kind: "image",
    provider: "local",
    ref: "/media/etapa-5/imagenes/evidencia-2.webp",
    availability: "available",
    description: "Evidencia 2: prompts usados.",
    fallback: "Evidencia 2 — próximamente.",
  },
  [mediaKey("stage5.rail.3")]: {
    key: mediaKey("stage5.rail.3"),
    kind: "image",
    provider: "local",
    ref: "/media/etapa-5/imagenes/evidencia-3.webp",
    availability: "available",
    description: "Evidencia 3: productos generados.",
    fallback: "Evidencia 3 — próximamente.",
  },
  [mediaKey("stage5.rail.4")]: {
    key: mediaKey("stage5.rail.4"),
    kind: "image",
    provider: "local",
    ref: "/media/etapa-5/imagenes/evidencia-4.webp",
    availability: "available",
    description: "Evidencia 4: comentarios y errores.",
    fallback: "Evidencia 4 — próximamente.",
  },
  [mediaKey("stage5.rail.5")]: {
    key: mediaKey("stage5.rail.5"),
    kind: "image",
    provider: "local",
    ref: "/media/etapa-5/imagenes/evidencia-5.webp",
    availability: "available",
    description: "Evidencia 5: ajustes y decisiones.",
    fallback: "Evidencia 5 — próximamente.",
  },

  // ── Etapa 6 ────────────────────────────────────────────────────────────────
  [mediaKey("stage6.evaluationDimensions")]: {
    key: mediaKey("stage6.evaluationDimensions"),
    kind: "image",
    provider: "local",
    ref: "/media/etapa-6/imagenes/dimensiones-evaluacion.webp",
    availability: "available",
    width: 2560,
    height: 1761,
    description: "Infografía: evaluar no es solo calificar (dimensiones pedagógica, técnica, ética, emocional y cognitiva).",
    fallback: "Infografía de dimensiones de evaluación — próximamente.",
  },
  [mediaKey("stage6.twoPerspectives")]: {
    key: mediaKey("stage6.twoPerspectives"),
    kind: "image",
    provider: "local",
    ref: "/media/etapa-6/imagenes/dos-miradas.webp",
    availability: "available",
    width: 2560,
    height: 1760,
    description: "Infografía: dos miradas sobre la experiencia (mirada docente y mirada estudiante).",
    fallback: "Infografía de dos miradas — próximamente.",
  },
  [mediaKey("stage6.evaluationCanvas")]: {
    key: mediaKey("stage6.evaluationCanvas"),
    kind: "download",
    provider: "local",
    ref: "/media/etapa-6/descargables/canvas-evaluacion/canvas-evaluacion.pdf",
    availability: "available",
    downloadName: "canvas-etapa-6-evaluacion.pdf",
    description: "Canvas de evaluación docente-estudiante de la experiencia mediada por IA (PDF).",
    fallback: "El Canvas de evaluación estará disponible para descarga próximamente.",
  },
  [mediaKey("stage6.evaluationCanvasPreview")]: {
    key: mediaKey("stage6.evaluationCanvasPreview"),
    kind: "image",
    provider: "local",
    ref: "/media/etapa-6/descargables/canvas-evaluacion/vista-previa.png",
    availability: "available",
    width: 1754,
    height: 1464,
    alt: "Previsualización del Canvas de la Etapa 6 para evaluar la experiencia mediada por IA desde las miradas docente y estudiantil.",
    description: "Previsualización del Canvas de evaluación docente-estudiante.",
    fallback: "La vista previa del Canvas de evaluación estará disponible próximamente.",
  },
  [mediaKey("stage6.newLoopVideo")]: {
    key: mediaKey("stage6.newLoopVideo"),
    kind: "video",
    provider: "http",
    ref: "/etapa-6/nueva-vuelta-espiral.mp4",
    availability: "pending",
    description: "Animación de cierre: la espiral continúa hacia una nueva vuelta.",
    fallback: "video de cierre: la espiral da una nueva vuelta (.mp4) — pendiente de subir",
    playback: TRANSITION_PLAYBACK,
  },

  // ── Transiciones entre capítulos (locales, ambientales) ───────────────────
  [mediaKey("transitions.introToStage1")]: {
    key: mediaKey("transitions.introToStage1"),
    kind: "video",
    provider: "local",
    ref: "/media/introduccion/videos/transicion-a-etapa-1.webm",
    availability: "available",
    description: "Animación de introducción al modelo.",
    fallback: "Animación de introducción al modelo — próximamente.",
    playback: TRANSITION_PLAYBACK,
  },
  [mediaKey("transitions.stage1ToStage2")]: {
    key: mediaKey("transitions.stage1ToStage2"),
    kind: "video",
    provider: "local",
    ref: "/media/etapa-1/videos/transicion-a-etapa-2.webm",
    availability: "available",
    description: "Animación de transición de la Etapa 1 a la Etapa 2.",
    fallback: "Animación de transición de Etapa 1 a 2 — próximamente.",
    playback: TRANSITION_PLAYBACK,
  },
  [mediaKey("transitions.stage2ToStage3")]: {
    key: mediaKey("transitions.stage2ToStage3"),
    kind: "video",
    provider: "local",
    ref: "/media/etapa-2/videos/transicion-a-etapa-3.webm",
    availability: "available",
    description: "Animación de transición de la Etapa 2 a la Etapa 3.",
    fallback: "Animación de transición de Etapa 2 a 3 — próximamente.",
    playback: TRANSITION_PLAYBACK,
  },
  [mediaKey("transitions.stage3ToStage4")]: {
    key: mediaKey("transitions.stage3ToStage4"),
    kind: "video",
    provider: "local",
    ref: "/media/etapa-3/videos/transicion-a-etapa-4.webm",
    availability: "available",
    description: "Animación de transición de la Etapa 3 a la Etapa 4.",
    fallback: "Animación de transición de Etapa 3 a 4 — próximamente.",
    playback: TRANSITION_PLAYBACK,
  },
  [mediaKey("transitions.stage4ToStage5")]: {
    key: mediaKey("transitions.stage4ToStage5"),
    kind: "video",
    provider: "local",
    ref: "/media/etapa-4/videos/transicion-a-etapa-5.webm",
    availability: "available",
    description: "Animación de transición de la Etapa 4 a la Etapa 5.",
    fallback: "Animación de transición de Etapa 4 a 5 — próximamente.",
    playback: TRANSITION_PLAYBACK,
  },
  [mediaKey("transitions.stage5ToStage6")]: {
    key: mediaKey("transitions.stage5ToStage6"),
    kind: "video",
    provider: "local",
    ref: "/media/etapa-5/videos/transicion-a-etapa-6.webm",
    availability: "available",
    description: "Animación de transición de la Etapa 5 a la Etapa 6.",
    fallback: "Animación de transición de Etapa 5 a 6 — próximamente.",
    playback: TRANSITION_PLAYBACK,
  },

  // ── Videos-resumen de cierre ─────────────────────────────────────────────
  [mediaKey("stage1.summaryVideo")]: {
    key: mediaKey("stage1.summaryVideo"),
    kind: "video",
    provider: "local",
    ref: "/media/etapa-1/videos/resumen.webm",
    availability: "available",
    description: "Video-resumen de cierre de la Etapa 1.",
    fallback: "Video-resumen — próximamente.",
    playback: SUMMARY_VIDEO_PLAYBACK,
  },
  [mediaKey("stage2.summaryVideo")]: {
    key: mediaKey("stage2.summaryVideo"),
    kind: "video",
    provider: "local",
    ref: "/media/etapa-2/videos/resumen.webm",
    availability: "available",
    description: "Video-resumen de cierre de la Etapa 2.",
    fallback: "Video-resumen — próximamente.",
    playback: SUMMARY_VIDEO_PLAYBACK,
  },
  [mediaKey("stage3.summaryVideo")]: {
    key: mediaKey("stage3.summaryVideo"),
    kind: "video",
    provider: "local",
    ref: "/media/etapa-3/videos/resumen.webm",
    availability: "available",
    description: "Video-resumen de cierre de la Etapa 3.",
    fallback: "Video-resumen — próximamente.",
    playback: SUMMARY_VIDEO_PLAYBACK,
  },
  [mediaKey("stage4.summaryVideo")]: {
    key: mediaKey("stage4.summaryVideo"),
    kind: "video",
    provider: "local",
    ref: "/media/etapa-4/videos/resumen.webm",
    availability: "available",
    description: "Video-resumen de cierre de la Etapa 4.",
    fallback: "Video-resumen — próximamente.",
    playback: SUMMARY_VIDEO_PLAYBACK,
  },
  [mediaKey("stage5.summaryVideo")]: {
    key: mediaKey("stage5.summaryVideo"),
    kind: "video",
    provider: "local",
    ref: "/media/etapa-5/videos/resumen.webm",
    availability: "available",
    description: "Video-resumen de cierre de la Etapa 5.",
    fallback: "Video-resumen — próximamente.",
    playback: SUMMARY_VIDEO_PLAYBACK,
  },
  [mediaKey("stage6.summaryVideo")]: {
    key: mediaKey("stage6.summaryVideo"),
    kind: "video",
    provider: "local",
    ref: "/media/etapa-6/videos/resumen.webm",
    availability: "available",
    description: "Video-resumen de cierre de la Etapa 6.",
    fallback: "Video-resumen — próximamente.",
    playback: SUMMARY_VIDEO_PLAYBACK,
  },

  // ── Abrebocas de apertura ────────────────────────────────────────────────
  [mediaKey("stage1.abrebocas")]: {
    key: mediaKey("stage1.abrebocas"),
    kind: "video",
    provider: "local",
    ref: "/media/etapa-1/videos/abrebocas.mp4",
    availability: "available",
    description: "Abrebocas de apertura de la Etapa 1.",
    fallback: "Video de apertura — próximamente.",
    playback: SUMMARY_VIDEO_PLAYBACK,
  },
  [mediaKey("stage2.abrebocas")]: {
    key: mediaKey("stage2.abrebocas"),
    kind: "video",
    provider: "local",
    ref: "/media/etapa-2/videos/abrebocas.mp4",
    availability: "available",
    description: "Abrebocas de apertura de la Etapa 2.",
    fallback: "Video de apertura — próximamente.",
    playback: SUMMARY_VIDEO_PLAYBACK,
  },
  [mediaKey("stage3.abrebocas")]: {
    key: mediaKey("stage3.abrebocas"),
    kind: "video",
    provider: "local",
    ref: "/media/etapa-3/videos/abrebocas.mp4",
    availability: "available",
    description: "Abrebocas de apertura de la Etapa 3.",
    fallback: "Video de apertura — próximamente.",
    playback: SUMMARY_VIDEO_PLAYBACK,
  },
  [mediaKey("stage4.abrebocas")]: {
    key: mediaKey("stage4.abrebocas"),
    kind: "video",
    provider: "local",
    ref: "/media/etapa-4/videos/abrebocas.mp4",
    availability: "available",
    description: "Abrebocas de apertura de la Etapa 4.",
    fallback: "Video de apertura — próximamente.",
    playback: SUMMARY_VIDEO_PLAYBACK,
  },
  [mediaKey("stage5.abrebocas")]: {
    key: mediaKey("stage5.abrebocas"),
    kind: "video",
    provider: "local",
    ref: "/media/etapa-5/videos/abrebocas.mp4",
    availability: "available",
    description: "Abrebocas de apertura de la Etapa 5.",
    fallback: "Video de apertura — próximamente.",
    playback: SUMMARY_VIDEO_PLAYBACK,
  },
  [mediaKey("stage6.abrebocas")]: {
    key: mediaKey("stage6.abrebocas"),
    kind: "video",
    provider: "local",
    ref: "/media/etapa-6/videos/abrebocas.mp4",
    availability: "available",
    description: "Abrebocas de apertura de la Etapa 6.",
    fallback: "Video de apertura — próximamente.",
    playback: SUMMARY_VIDEO_PLAYBACK,
  },

} satisfies MediaManifest;
